services:
  api:
    image: liquor-license-api
    build:
      context: ./api
      dockerfile: Dockerfile
      target: build
    container_name: liquor-license-api
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    volumes:
      - ./api/src:/api/src
      - /api/node_modules
    command: npm run dev
